name: Deploy to Cloud Run

permissions:
  contents: read
  id-token: write
  actions: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Debug GCP credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: neliti-480014

    - name: Use gcloud CLI
      run: 'gcloud info'

    - name: Configure Docker authentication
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        cd backend
        docker build -t asia-southeast1-docker.pkg.dev/neliti-480014/research-repo/research-backend:latest .
        docker push asia-southeast1-docker.pkg.dev/neliti-480014/research-repo/research-backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy research-data-backend \
          --image asia-southeast1-docker.pkg.dev/neliti-480014/research-repo/research-backend:latest \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --concurrency 80 \
          --max-instances 10 \
          --set-env-vars MONGOSTRING="${{ secrets.MONGOSTRING }}" \
          --set-env-vars PRIVATEKEY="${{ secrets.PRIVATEKEY }}" \
          --set-env-vars PUBLICKEY="${{ secrets.PUBLICKEY }}" \
          --set-env-vars JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          --set-env-vars GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" \
          --set-env-vars ENVIRONMENT=production
